<?php
$productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$slideToShow = $block->getData('slidetoshow');
$check = ($block->getData('displaytype') == 'slider') ? 1 : 0;
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('AHT\Featured\Helper\Data'); 
?>
<?php if($helper->isEnable()) : ?>
<div class="block widget block-products-list grid">
    <div class="block-title">
   	 <h2><?php echo $block->getTitle() ?></h2>
    </div>
    <div class="block-content">
   	 <?php if (count($productCollection)): ?>
   		 <div class="products-grid grid ">
			<ol class="regular product-items widget-product-grid">
				<?php foreach ($productCollection as $product): ?>
				<li class="product-item">
   			 	<div class="product-item-info">
   				 <div class="product-image">
   					 <a href="<?php echo $product->getProductUrl() ?>">
   						 <?php echo $block->getImage($product, 'category_page_grid')->toHtml() ?>
   					 </a>
   				 </div>
   				 <strong class="product-name">
   					 <a href="<?php echo $product->getProductUrl() ?>">
   						 <?php echo $_helper->productAttribute($product, $product->getName(), 'name'); ?>
   					 </a>
   				 </strong>
   				 <?php echo $block->getProductPrice($product) ?>
					</div>
				</li>
				<?php endforeach; ?>
			</ol>
   		 </div>
   	 <?php endif; ?>
    </div>
</div>
<?php if($check){
  echo '<script type="text/javascript">'."
		require(['jquery', 'slick'], function($){
		$(function(){
			$('.regular').slick({
				dots: false,
				infinite: false,
				speed: 300,
				slidesToShow: ".$slideToShow.",
				slidesToScroll: 1,
				responsive: [
					{
						breakpoint: 1024,settings: {
						slidesToShow: 4,
						slidesToScroll: 1,
						infinite: true
					}
					},
					{
						breakpoint: 770,
						settings: {
							slidesToShow: 3,
							slidesToScroll: 2
						}
					},
					{
						breakpoint: 600,
						settings: {
							slidesToShow: 2,
							slidesToScroll: 2
						}
					},
					{
						breakpoint: 400,
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1
						}
					}
				]
			});
		});
		});
	</script>";
	};
?>
<?php endif; ?>




